### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by NewtTheWolf**
from a legal point of view you are not allowed to use unlicensed stuff, so I recommend at least an MIT license.

### CODE REVIEW

**Comment by NewtTheWolf** [comment]
https://choosealicense.com/no-permission/

**Comment by UrielCh** [comment]
oups

**Comment by UrielCh** [comment]
After double-checking, this project was meant to be released as GPL3.0, as described in package.json.
But the GPL is too large for a nodeJS project.

so I should switch to a more classic license...

**Comment by NewtTheWolf** [comment]
may i ask why you want to use a GPL3.0 license?

because as far as I have now informed myself it will not be possible for my project to use your modules which is a pity

so i have no problem giving credits and all, but it's more about the software i want to write being closed source, but if i use your module i have to release my software with a GPL3.0 compatible license

which license would you plan to use?

**Comment by NewtTheWolf** [comment]
may i ask why you want to use a GPL3.0 license?

because as far as I have now informed myself it will not be possible for my project to use your modules which is a pity

so i have no problem giving credits and all, but it's more about the software i want to write being closed source, but if i use your module i have to release my software with a GPL3.0 compatible license

which license would you plan to use?

edit:

i'm discussing with several people right now, if i'm wrong feel free to correct me

**Comment by UrielCh** [comment]
Proxmox is released under GPL 3, so in this project too, I did not spend more time on choosing the license.

**Pull request closed without merging**
